sudo: required
dist: trusty

os:
  - linux
# TODO https://github.com/Microsoft/vscode-mssql/issues/1004 reenable OSX once travis issue is fixed
#  - osx

mono: none
dotnet: 2.0.0

# safelist
branches:
  only:
    - master
    - dev

language: csharp

env:
  # Since we are building from root, current directory is the project path
  - ProjectPath=$TRAVIS_BUILD_DIR
  - HOMEBREW_NO_AUTO_UPDATE=1
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install dotnet-sdk-2.0.0;
    else
      brew update;
    fi

install:
  - dotnet restore sqltoolsservice.sln
  - dotnet restore Microsoft.SqlTools.Dmp.sln

script:
  - dotnet build src/Microsoft.SqlTools.ServiceLayer
  - dotnet build src/Microsoft.SqlTools.Dmp.Hosting
  - dotnet test test/Microsoft.SqlTools.ServiceLayer.UnitTests
  - dotnet test test/Microsoft.SqlTools.Dmp.Hosting.UnitTests

