trigger: none
pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
    name: 'ads-build-1es-hosted-pool'
    demands:
    ImageOverride -equals ADS-Windows_Image
    steps:
    - template: build.yml

- stage: Release
  variables:
  - name: skipComponentGovernanceDetection
    value: true
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['RELEASE'], 'true'))
  pool: 
    name: 'ads-build-1es-hosted-pool'
    demands:
    ImageOverride -equals ADS-Linux_Image
  jobs:
  - job: Release
    steps:
    - template: release.yml
