trigger: none
pr: none

variables:
  # Major version number for the release
- name: Major
  value: '5'
  # Minor version number for the release (should be incremented post a stable release)
- name: Minor
  value: '0'
  # Patch version number for the release (should be incremented in release branch once one is created)
- name: Patch
  value: '0'

stages:
- stage: Build
  variables:
  - name: buildConfiguration
    value: 'Release'
  - name: ManagedBatchParserMajor
    value: '4'
  - name: ManagedBatchParserMinor
    value: '0'
    # Set to true to build a stable release.
  - name: StableRelease
    value: 'false'
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: build.yml
    timeoutInMinutes: 150 # temporary while investigating timeout occurring in STS Product Build pipeline; should return to 90 after