trigger: none
pr: none

stages:
- stage: Build
  variables:
  - name: buildConfiguration
    value: 'Release'
    # Major version number for the release
  - name: Major
    value: '3'
    # Minor version number for the release (should be incremented post a stable release)
  - name: Minor
    value: '0'
    # Set to true to build a stable release.
  - name: StableRelease
    value: 'false'
  jobs:
  - job: Build
    pool: 
      name: 'ads-build-1es-hosted-pool'
      demands:
      - ImageOverride -equals ADS-Windows_Image
    steps:
    - template: build.yml
    timeoutInMinutes: 90

- stage: Release
  variables:
  - name: skipComponentGovernanceDetection
    value: true
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['RELEASE'], 'true'))
  pool: 
    name: 'ads-build-1es-hosted-pool'
    demands:
    - ImageOverride -equals ADS-Linux_Image
  jobs:
  - job: Release
    steps:
    - template: release.yml
